version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-authuser
    environment:
      POSTGRES_DB: authuser
      POSTGRES_USER: joel
      POSTGRES_PASSWORD: docker
    ports:
      - "5433:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
