server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'


spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authuser
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost